import { escape, badge, icon, urlFor } from './ui.mjs';
import { TERMINAL, supportsRepair } from './execution-api.mjs';
import { supervisionView, environmentView, operationRecoveryView } from './supervision-ui.mjs';
const json = (value) => escape(JSON.stringify(value, null, 2));
const detail = (label, value, key) => `<details class="disclosure" data-key="${escape(key)}"><summary>${escape(label)} ${icon('down')}</summary><pre>${json(value)}</pre></details>`;
const status = (value) => value.replaceAll('_', ' ');
export function executionPanel(s, draft, { debuggerView = false, allowNewTask = false, unavailable = false, feedbackDraft = '' } = {}) {
  const run = s.run;
  const disabled = s.busy || !!s.pending || !!s.operationPending || s.operationRecovery || s.recovery || !s.connected || unavailable;
  const supervised = draft.supervised !== false;
  const repairSupported = supportsRepair(s.runtime, draft.scenario);
  const repair = supervised && !!draft.repair_enabled;
  const omission = supervised && !repair && !!draft.demo_omit_notification;
  const canStart = !disabled && s.runtime?.execution_enabled && !s.runtime.active_run_id && (s.taskId || allowNewTask) && (!supervised || s.runtime.supervision_enabled) && (!repair || (repairSupported && s.repairRuntime?.available));
  const runtime = !s.connected ? 'Reconnect to inspect execution availability.' : !s.runtime ? 'Reading execution availability…' :
    !s.runtime.hermes_available ? 'Hermes installation is unavailable on this server.' :
      !s.runtime.execution_enabled ? 'Execution is disabled or the server has unresolved execution state.' :
        s.runtime.active_run_id ? `Executor busy · run ${s.runtime.active_run_id}` : 'Release execution is available. Provider connectivity has not been tested.';
  const frozen = s.pending;
  const form = `<section class="release-controls"><h2>Release demo controls</h2><p>Create a release ticket, attach the required checklist, then send QA both links. Optional Luna supervision interprets supported additions from your request and checks progress.</p><p class="intake-stale" data-runtime>${escape(runtime)}</p>
    <form id="release-form"><div class="release-fields"><div><label for="release-value">Release</label><input id="release-value" value="${escape(draft.release)}" required ${disabled ? 'disabled' : ''}></div>
    <div><label for="release-scenario">Sandbox scenario</label><select id="release-scenario" ${disabled ? 'disabled' : ''}>${[['control', 'Healthy control'], ['broken_checklist', 'Broken checklist'], ['missing_lookup', 'Missing owner lookup'], ['outdated_context', 'Outdated guidance']].map(([value, label]) => `<option value="${value}" ${draft.scenario === value ? 'selected' : ''}>${label}</option>`).join('')}</select></div></div>
    <fieldset class="release-options"><legend>Agent supervision</legend><label><input id="release-supervised" type="checkbox" ${supervised ? 'checked' : ''} ${disabled ? 'disabled' : ''}> Supervise with Luna</label><p>Plan sourced checkpoints, verify outcomes and direct Hermes to complete missing steps.</p><label><input id="release-repair" type="checkbox" ${repair ? 'checked' : ''} ${disabled || !supervised || !repairSupported || !s.repairRuntime?.available ? 'disabled' : ''}> Enable generated environment repair</label><p>Generate and verify a supported checklist, owner lookup or guidance repair in Docker before publication. Requires the matching server capability and an available repair runner.</p><label><input id="release-omission" type="checkbox" ${omission ? 'checked' : ''} ${disabled || !supervised || repair ? 'disabled' : ''}> Demonstrate an omitted QA notification</label><p>This deliberately staged omission demonstrates a supervisor correction. It cannot be combined with repair.</p></fieldset>
    ${supervised && !s.runtime?.supervision_enabled ? '<p class="notice">Supervision is unavailable. Inspect the server debugger setup, or turn supervision off for direct execution.</p>' : ''}
    <details class="disclosure" data-key="release-limits"><summary>Execution limits ${icon('down')}</summary><div class="release-fields"><div><label for="release-turns">Maximum model requests</label><input id="release-turns" type="number" min="1" max="20" value="${escape(draft.max_turns ?? 20)}" required ${disabled ? 'disabled' : ''}></div><div><label for="release-timeout">Timeout in seconds</label><input id="release-timeout" type="number" min="10" max="600" value="${escape(draft.timeout_seconds ?? 600)}" required ${disabled ? 'disabled' : ''}></div></div><p>Debugger and Hermes share the operation budget. Repair gives isolated verification separate stage budgets, with an overall ceiling of three times these limits and two candidates. Request counts are not a dollar cost.</p></details>
    <p class="intake-stale">Business effects stay in local simulations. Starting uses the server’s configured Hermes model. A new run uses a separate sandbox.</p><button id="start-release" ${canStart ? '' : 'disabled'}>${s.busy ? 'Sending…' : 'Run release evaluation'}</button></form></section>`;
  const recovery = frozen ? `<section class="pending-card"><h2>${s.rejected ? 'Run request rejected' : 'Run submission awaiting confirmation'}</h2><p>The exact request, task and server are retained. No automatic execution retry occurs.</p><code>${escape(frozen.payload.client_request_id)}</code>${detail('Inspect frozen run request', frozen, 'run-pending')}${frozen.taskId !== s.taskId || frozen.origin !== s.origin ? `<p>Connect to ${escape(frozen.origin)} and <a data-route href="${urlFor(false, 'debugger', frozen.taskId)}">open the original task</a> to reconcile.</p>` : s.rejected ? '<button data-action="run-review">Return rejected run to form</button>' : `<button data-action="run-retry" ${s.busy || !s.connected || s.recovery ? 'disabled' : ''}>Retry exact run request</button>`}</section>` : '';
  const history = s.runs.length ? `<div class="run-history"><label for="run-history">Run history</label><select id="run-history" ${s.busy ? 'disabled' : ''}>${s.runs.map((item) => `<option value="${escape(item.id)}" ${item.id === run?.id ? 'selected' : ''}>${escape(item.request.release)} · ${escape(status(item.status))} · ${escape(item.created_at)} · ${escape(item.id)}</option>`).join('')}</select></div>` : '';
  let evidence = '';
  if (run) {
    const checkpoints = run.brief.checkpoints.map((c) => `<li class="live-checkpoint"><div class="inline-row"><strong>${escape(c.description)}</strong>${badge(c.status === 'verified' ? 'passed' : c.status, status(c.status))}</div><p>${escape(c.verification_rule)}</p>${c.uncertainty ? `<p class="notice">${escape(c.uncertainty)}</p>` : ''}${detail('Sources, dependencies and evidence', c, `checkpoint-${c.id}`)}</li>`).join('');
    const verification = run.verification ? `<p data-verdict>Trusted checks: ${run.verification.passed ? 'passed' : 'failed'}</p><ul class="verification-checks">${run.verification.checks.map((c) => `<li>${badge(c.passed ? 'passed' : 'failed', c.passed ? 'Passed' : 'Failed')} ${escape(c.name)}</li>`).join('')}</ul>${detail('Verification evidence and digests', run.verification, `verification-${run.id}`)}` : '<p data-verdict>Trusted verification is not available yet.</p>';
    const effects = s.snapshot ? ['tickets', 'checklists', 'messages'].map((kind) => `<section><h3>${kind[0].toUpperCase() + kind.slice(1)} (${s.snapshot[kind].length})</h3>${s.snapshot[kind].map((item, index) => detail(item.title || item.text || item.id || `${kind} ${index + 1}`, item, `${run.id}-${kind}-${index}`)).join('') || '<p>No recorded objects.</p>'}</section>`).join('') : '<p>Simulated state is not loaded.</p>';
    evidence = `<section class="live-run" data-run-id="${escape(run.id)}"><div class="inline-row"><h2>Release ${escape(run.request.release)}</h2><span data-run-status>${badge(run.status, status(run.status))}</span></div><p class="intake-stale">${escape(run.request.scenario)} · activity ${escape(s.stream)} · ${s.events.length} persisted events</p><code class="run-id">${escape(run.id)}</code><div class="run-actions"><button data-action="run-refresh" ${s.loading || !s.connected ? 'disabled' : ''}>Refresh run evidence</button>${!TERMINAL.has(run.status) ? `<button data-action="run-cancel" ${s.busy || !s.connected ? 'disabled' : ''}>Request cancellation</button>` : ''}</div>
    <section class="evaluation-summary"><h3>Evaluation outcome</h3>${run.verification ? `<p>${run.verification.checks.filter(c => c.passed).length} checks passed · ${run.verification.checks.filter(c => !c.passed).length} failed</p><ul>${run.verification.checks.filter(c => !c.passed).map(c => `<li>${escape(c.name)}</li>`).join('')}</ul>` : '<p>Evaluation has not produced a trusted result yet.</p>'}${run.error ? `<p>${escape(run.error.message)}</p>` : ''}${run.missing_evidence.length ? `<p>${run.missing_evidence.length} evidence gaps remain; inspect missing evidence below.</p>` : ''}<p>${run.verification?.passed ? 'The recorded release checks passed. Repair publication is reported separately below.' : 'Inspect the checkpoint and diagnosis evidence below for the recorded causes and limitations.'}</p></section>
    <h3>Checkpoints</h3><p>These are backend checkpoint verdicts. They update during trusted verification.</p><ol class="live-checkpoints">${checkpoints}</ol>${detail('Structured task brief', run.brief, `brief-${run.id}`)}
    <section class="trusted-result"><h3>Trusted result</h3>${verification}</section>
    <section><h3>${run.supervision ? 'Delivery or supervisor response' : 'Executor response'}</h3><p>Executor conversation finished: ${run.executor_success == null ? 'unknown' : run.executor_success ? 'yes' : 'no'}. This alone does not prove task completion.</p><div class="executor-response">${escape(run.final_response ?? 'No final response recorded.')}</div></section>
    ${supervisionView(s, feedbackDraft)}
    ${run.error ? detail('Execution error', run.error, `error-${run.id}`) : ''}${run.missing_evidence.length ? `<section class="notice"><h3>Missing evidence</h3><ul>${run.missing_evidence.map((x) => `<li>${escape(x)}</li>`).join('')}</ul></section>` : ''}
    <section class="simulated-effects"><h3>Recorded simulated objects</h3><p>References beginning with simulated:// identify local objects. Inspect them here; they are not external service links. Partial effects remain after failure or cancellation.</p>${effects}${s.snapshot ? detail('Full sandbox state and retained context', s.snapshot, `state-${run.id}`) : ''}</section>
    <details class="disclosure" data-key="activity-${escape(run.id)}" ${debuggerView ? 'open' : ''}><summary>Execution activity (${s.events.length}) ${icon('down')}</summary><ol class="live-events">${s.events.map((event) => `<li data-sequence="${event.sequence}">${detail(`${event.sequence} · ${event.type} · ${event.emitted_at}`, event.payload, `event-${run.id}-${event.sequence}`)}</li>`).join('')}</ol></details>${detail('Complete execution record and baseline', run, `record-${run.id}`)}</section>`;
  }
  return `<div class="execution-panel">${s.error ? `<p class="alert" role="alert">${escape(s.error)}</p>` : ''}${s.notice ? `<p class="notice" data-run-notice>${escape(s.notice)}</p>` : ''}${s.recovery ? '<p class="alert">Run recovery is uncertain. New executions are blocked.</p>' : ''}${recovery}${operationRecoveryView(s)}${run ? `${history}${evidence}<details class="disclosure" data-key="another-release"><summary>Start another release run ${icon('down')}</summary>${form}</details>` : form}${environmentView(s)}${s.optionalErrors?.length ? `<section class="notice"><h3>Some inspection data is unavailable</h3><ul>${s.optionalErrors.map((error) => `<li>${escape(error)}</li>`).join('')}</ul><p>Loaded run evidence remains visible. Refresh to retry these read-only inspections.</p></section>` : ''}${s.runtime?.development_validation === 'phases_6_7_untested' ? '<p class="notice">The backend reports that lookup and guidance repair development acceptance is pending. Runtime verification is still required before publication.</p>' : ''}<p class="intake-stale">Live evidence above comes from this backend. Business effects are local simulations. Repair availability comes from this server. The separate demo page contains authored fixtures.</p></div>`;
}
