import { escape, badge, icon } from './ui.mjs';

export const incidentURL = (id = '', project = '', offset = 0) => {
  const query = new URLSearchParams();
  if (id) query.set('incident', id);
  if (project) query.set('project', project);
  if (offset) query.set('offset', String(offset));
  return `/incidents${query.size ? `?${query}` : ''}`;
};
const details = (label, value, key) => `<details class="disclosure" data-key="${escape(key)}"><summary>${escape(label)} ${icon('down')}</summary><pre>${escape(JSON.stringify(value, null, 2))}</pre></details>`;
const warnings = (values) => values?.length ? `<ul class="notice">${values.map((value) => `<li>${escape(value)}</li>`).join('')}</ul>` : '';
const citedEvidence = (ids, available) => (ids || []).map((id) => available.has(id) ? `<a class="text-button" href="#evidence-${escape(id)}">Evidence ${escape(id)}</a>` : `<span class="notice">Cited evidence unavailable: ${escape(id)}</span>`).join(' ');
function sourceLink(reference, origin) {
  if (typeof reference !== 'string') return '';
  try {
    const local = /^\/api\/(?:telemetry\/traces\/[0-9a-f]+\/spans\/[0-9a-f]+|runs\/[0-9a-f-]+\/trace|evidence\/[0-9a-f-]+)$/.test(reference);
    if (!local && !/^https?:\/\//.test(reference)) return '';
    const url = new URL(reference, origin);
    if (!['http:', 'https:'].includes(url.protocol) || url.username || url.password) return '';
    return `<a class="text-button" href="${escape(url.href)}" target="_blank" rel="noopener noreferrer">Open source reference ${icon('arrow')}</a>`;
  } catch { return ''; }
}
function incidentDetail(incident, locked, question, origin) {
  if (!incident) return '<p>Select an incident to inspect its evidence and ask a question.</p>';
  const evidence = incident.evidence || [], available = new Set(evidence.map((item) => item.id));
  const recurrence = incident.recurrence || {};
  const runTask = (runId) => evidence.find((item) => item.run_id === runId && item.task_id)?.task_id;
  return `<article class="incident-detail" data-incident-id="${escape(incident.id)}"><div class="inline-row"><h2>${escape(incident.title)}</h2>${badge(incident.status)}</div><p>${escape(incident.project_id)} · ${escape(incident.workflow || 'workflow not recorded')} · ${escape(incident.evidence_count)} evidence records</p>
    ${warnings(incident.warnings)}<section><h3>Recurrence in comparable runs</h3><p>Before: ${escape(recurrence.before?.affected ?? 'unknown')} affected / ${escape(recurrence.before?.comparable ?? 'unknown')} comparable. After: ${escape(recurrence.after?.affected ?? 'unknown')} affected / ${escape(recurrence.after?.comparable ?? 'unknown')} comparable.</p><p>Recovered runs: ${escape(recurrence.recovered_runs ?? 0)} · Verification runs: ${escape(recurrence.verification_runs ?? 0)} · Excluded runs: ${escape(recurrence.excluded_runs ?? 0)}.</p><p>These counts describe recorded observations. Recovery of one task and fewer later failures are separate claims.</p>${details('Recurrence calculation', recurrence, 'incident-recurrence')}</section>
    <section><h3>Related runs and repairs</h3><ul>${(incident.run_ids || []).map((id) => `<li>${runTask(id) ? `<a data-route href="/debugger?task=${encodeURIComponent(runTask(id))}&run=${encodeURIComponent(id)}">Inspect run ${escape(id)}</a>` : `Run ${escape(id)} · no task link recorded`}</li>`).join('') || '<li>No linked runs recorded.</li>'}</ul>${(incident.repairs || []).map((repair, index) => details(`Repair ${repair.id || index + 1} · ${repair.status || 'unknown'}`, repair, `incident-repair-${index}`)).join('') || '<p>No repair recorded. Incident analysis cannot publish an environment change.</p>'}</section>
    <section><h3>Evidence and membership decisions</h3><p>Imported reports are untrusted observations. Trusted execution facts retain their source identity.</p>${evidence.map((item) => `<article class="incident-evidence" id="evidence-${escape(item.id)}"><h4>${escape(item.source_type)} · ${escape(item.source_id)}</h4><p>${badge(item.trusted ? 'passed' : 'pending', item.trusted ? 'Trusted native fact' : 'Untrusted observation')} · ${escape(item.timestamp)}</p><p class="executor-response">${escape(item.text)}</p>${(incident.decisions || []).filter((decision) => decision.evidence_id === item.id).map((decision) => `<p>Membership: ${escape(decision.decision)}</p><ul>${(decision.reasons || []).map((reason) => `<li>${escape(reason)}</li>`).join('')}</ul>`).join('')}${sourceLink(item.source_ref, origin)}${details('Full source record and correlation', item, `incident-evidence-${item.id}`)}</article>`).join('') || '<p>No evidence retained.</p>'}${details('All grouping decisions, including exclusions', incident.decisions || [], 'incident-decisions')}</section>
    <section><h3>Ask Luna about this incident</h3><p>Each explicit action uses one bounded model request. Answers are explanations and hypotheses; trusted checks still determine task success.</p><button data-action="incident-analyze" ${locked ? 'disabled' : ''}>Analyze incident</button><form id="incident-question-form"><label for="incident-question">Question</label><textarea id="incident-question" rows="3" required ${locked ? 'disabled' : ''}>${escape(question)}</textarea><button ${locked ? 'disabled' : ''}>Ask question</button></form>${(incident.analyses || []).map((analysis, index) => `<article class="incident-analysis"><h4>Recorded analysis · ${escape(analysis.status)}</h4>${analysis.question ? `<p>${escape(analysis.question)}</p>` : ''}<p class="executor-response">${escape(analysis.answer || 'No answer recorded.')}</p><p>${citedEvidence(analysis.evidence_ids, available)}</p>${details('Hypotheses', analysis.hypotheses || [], `incident-analysis-${index}-hypotheses`)}${details('Missing evidence', analysis.missing_evidence || [], `incident-analysis-${index}-missing`)}${analysis.error ? details('Analysis error', analysis.error, `incident-analysis-${index}-error`) : ''}</article>`).join('')}</section></article>`;
}
export function incidentsView(s, { importDraft = '', questionDraft = '', projectDraft = s.project } = {}) {
  const locked = !s.connected || s.busy || !!s.pending || s.recovery;
  const pending = s.pending;
  return `<div class="debugger incidents-page execution-panel"><header class="debug-heading"><p class="eyebrow">Epoch / incidents</p><h1>Incidents</h1><p>Connect execution failures with trace, Slack and support evidence. Inspect why records belong together before drawing a conclusion.</p></header>
    ${s.error ? `<p class="alert" role="alert">${escape(s.error)}</p>` : ''}${s.notice ? `<p class="notice">${escape(s.notice)}</p>` : ''}${warnings(s.warnings)}${warnings(s.list?.warnings)}${s.recovery ? '<p class="alert">Incident request recovery is unavailable. Reads remain available; restore the saved request before new actions.</p>' : ''}
    ${pending ? `<section class="pending-card"><h2>${s.rejected ? 'Incident action rejected' : 'Incident action awaiting confirmation'}</h2><p>Request ${escape(pending.payload.client_request_id)} is retained. Retrying asks for the same saved result.</p>${details('Exact saved request', pending, 'incident-pending')}${pending.origin !== s.origin ? `<p>Reconnect to ${escape(pending.origin)} to resolve this action.</p>` : s.rejected ? '<button data-action="incident-review">Review rejected request</button>' : `<button data-action="incident-retry" ${s.busy || !s.connected ? 'disabled' : ''}>Retry exact incident request</button>`}</section>` : ''}
    <section class="environment-panel"><h2>Telemetry connection</h2><p>Local collection and Neatlogs cloud delivery are separate. No credentials are entered in this interface.</p>${s.telemetry ? `<p>Local collector: ${s.telemetry.collector_ready ? 'ready' : 'not ready'} · Cloud export: ${s.telemetry.cloud_enabled ? s.telemetry.cloud_configured ? 'configured' : 'credentials missing' : 'disabled'} · Cloud export accepted: ${s.telemetry.cloud_export_accepted ? 'recorded' : 'not recorded'} · Cloud readback: ${s.telemetry.cloud_readback_verified ? 'verified' : 'not verified'}.</p><p>Stored spans: ${escape(s.telemetry.stored_spans ?? 0)} · Queued: ${escape(s.telemetry.queued ?? 0)} · Accepted exports: ${escape(s.telemetry.delivered ?? 0)} · Failed: ${escape(s.telemetry.failed ?? 0)}.</p>${warnings(s.telemetry.warnings)}${details('Collector readiness and delivery status', s.telemetry, 'incident-telemetry')}` : '<p>Telemetry status is unavailable. Connect or refresh to inspect it.</p>'}</section>
    <form id="incident-filter-form" class="release-fields"><div><label for="incident-project">Project filter</label><input id="incident-project" value="${escape(projectDraft)}" placeholder="All projects"></div><div class="run-actions"><button ${!s.connected ? 'disabled' : ''}>Apply filter</button><button type="button" data-action="incident-refresh" ${s.loading || !s.connected ? 'disabled' : ''}>Refresh incidents</button></div></form>
    <ul class="incident-list">${(s.list?.items || []).map((item) => `<li><a data-route href="${incidentURL(item.id, s.project, s.offset)}" ${item.id === s.selected ? 'aria-current="page"' : ''}><strong>${escape(item.title)}</strong><span>${escape(item.project_id)} · ${escape(item.status)} · ${escape(item.evidence_count)} records</span></a></li>`).join('') || `<li>${s.connected ? s.loading ? 'Loading incidents…' : 'No incidents loaded for this project.' : 'Connect to your local backend to inspect incidents.'}</li>`}</ul>
    ${s.list ? `<div class="pagination">${s.offset ? `<a data-route href="${incidentURL('', s.project, Math.max(0, s.offset - 50))}">Newer</a>` : ''}<span>${s.list.total} incidents</span>${s.offset + s.list.items.length < s.list.total ? `<a data-route href="${incidentURL('', s.project, s.offset + 50)}">Older</a>` : ''}</div>` : ''}
    <details class="disclosure" data-key="incident-import"><summary>Import Slack or support reports ${icon('down')}</summary><p>Provide exported JSON records. Importing evidence does not start execution or grant repair permission.</p>${details('Required JSON format', [{ source_type: 'support', source_id: 'ticket-123', timestamp: '2026-09-06T10:00:00Z', project_id: 'demo', text: 'The QA notification was missing.' }], 'incident-import-example')}<label for="incident-import-file">Load a JSON file</label><input id="incident-import-file" type="file" accept=".json,application/json" ${locked ? 'disabled' : ''}><form id="incident-import-form"><label for="incident-import-json">JSON records</label><textarea id="incident-import-json" rows="8" required ${locked ? 'disabled' : ''}>${escape(importDraft)}</textarea><button ${locked ? 'disabled' : ''}>Import evidence</button></form></details>
    ${incidentDetail(s.incident, locked, questionDraft, s.origin)}</div>`;
}
